# This is a basic workflow to help you get started with Actions

name: Check PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test ENV
        env:
          TEAM_NAME: $((echo ${{ github.ref }} | cut -f3 -d/))
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo ${{ env.TEAM_NAME }}
          echo ${{ env.BUILD_NUMBER }}
          echo ${{ github.base_ref }}
          echo ${{ github.run_number }}
